### ISSUE TITLE
提示 “EOF occurred in violation of protocol” 无法下载，能否更新

### ISSUE THREAD

**Issue by jiucenglou** [DertahSama/Download_SS_PDF#10]
提示 “EOF occurred in violation of protocol” 无法下载，能否更新， 感谢！

[code]
PS D:\Downloads> .\Download_SS_PDF.ver1.8.exe
Download_SS_PDF-ver1.8, by DertahSama, 2022.10.5
这是一个从超星图书馆（http://www.sslibrary.com ）下载PDF并且自动添加目录和压缩、并且支持选页下载的python脚本，然后打包成了exe。
本项目地址：https://github.com/DertahSama/Download_SS_PDF

输入阅读页面网址（页面不要关）：https://img.sslibrary.com/n/slib/book/slib/10253709/373cc3111f99438f95ac0fa5af4bd670/ec8de8a852b0df94e81d781e6f882466.shtml?dxbaoku=false&moocbaoku=false&deptid=147&fav=https%3A%2F%2Fwww.sslibrary.com%2Freader%2Fpdg%2Fpdgreader%3Fd%3D3eabcf181fd8507a983e18fba70763dd%26ssid%3D10253709&fenlei=130408010201&spage=1&t=5&username=219.142.99.12&view=-1
开始获取信息……
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 499, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='img.sslibrary.com', port=443): Max retries exceeded with url: /n/slib/book/slib/10253709/373cc3111f99438f95ac0fa5af4bd670/ec8de8a852b0df94e81d781e6f882466.shtml?dxbaoku=false&moocbaoku=false&deptid=147&fav=https%3A%2F%2Fwww.sslibrary.com%2Freader%2Fpdg%2Fpdgreader%3Fd%3D3eabcf181fd8507a983e18fba70763dd%26ssid%3D10253709&fenlei=130408010201&spage=1&t=5&username=219.142.99.12&view=-1&Upgrade-Insecure-Requests=1&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F86.0.4240.198+Safari%2F537.36&Accept=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2Cimage%2Favif%2Cimage%2Fwebp%2Cimage%2Fapng%2C%2A%2F%2A%3Bq%3D0.8%2Capplication%2Fsigned-exchange%3Bv%3Db3%3Bq%3D0.9&Accept-Encoding=gzip%2C+deflate%2C+br&Accept-Language=zh-CN%2Czh%3Bq%3D0.9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Download_SS_PDF ver1.8.py", line 434, in <module>
  File "Download_SS_PDF ver1.8.py", line 404, in main
  File "Download_SS_PDF ver1.8.py", line 65, in GetData
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='img.sslibrary.com', port=443): Max retries exceeded with url: /n/slib/book/slib/10253709/373cc3111f99438f95ac0fa5af4bd670/ec8de8a852b0df94e81d781e6f882466.shtml?dxbaoku=false&moocbaoku=false&deptid=147&fav=https%3A%2F%2Fwww.sslibrary.com%2Freader%2Fpdg%2Fpdgreader%3Fd%3D3eabcf181fd8507a983e18fba70763dd%26ssid%3D10253709&fenlei=130408010201&spage=1&t=5&username=219.142.99.12&view=-1&Upgrade-Insecure-Requests=1&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F86.0.4240.198+Safari%2F537.36&Accept=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2Cimage%2Favif%2Cimage%2Fwebp%2Cimage%2Fapng%2C%2A%2F%2A%3Bq%3D0.8%2Capplication%2Fsigned-exchange%3Bv%3Db3%3Bq%3D0.9&Accept-Encoding=gzip%2C+deflate%2C+br&Accept-Language=zh-CN%2Czh%3Bq%3D0.9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[56184] Failed to execute script 'Download_SS_PDF ver1.8' due to unhandled exception!
PS D:\Downloads> .\Download_SS_PDF.ver1.8.exe
Download_SS_PDF-ver1.8, by DertahSama, 2022.10.5
这是一个从超星图书馆（http://www.sslibrary.com ）下载PDF并且自动添加目录和压缩、并且支持选页下载的python脚本，然后打包成了exe。
本项目地址：https://github.com/DertahSama/Download_SS_PDF

输入阅读页面网址（页面不要关）：https://img.sslibrary.com/n/slib/book/slib/10253709/373cc3111f99438f95ac0fa5af4bd670/ec8de8a852b0df94e81d781e6f882466.shtml
开始获取信息……
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 499, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='img.sslibrary.com', port=443): Max retries exceeded with url: /n/slib/book/slib/10253709/373cc3111f99438f95ac0fa5af4bd670/ec8de8a852b0df94e81d781e6f882466.shtml?Upgrade-Insecure-Requests=1&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F86.0.4240.198+Safari%2F537.36&Accept=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2Cimage%2Favif%2Cimage%2Fwebp%2Cimage%2Fapng%2C%2A%2F%2A%3Bq%3D0.8%2Capplication%2Fsigned-exchange%3Bv%3Db3%3Bq%3D0.9&Accept-Encoding=gzip%2C+deflate%2C+br&Accept-Language=zh-CN%2Czh%3Bq%3D0.9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Download_SS_PDF ver1.8.py", line 434, in <module>
  File "Download_SS_PDF ver1.8.py", line 404, in main
  File "Download_SS_PDF ver1.8.py", line 65, in GetData
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='img.sslibrary.com', port=443): Max retries exceeded with url: /n/slib/book/slib/10253709/373cc3111f99438f95ac0fa5af4bd670/ec8de8a852b0df94e81d781e6f882466.shtml?Upgrade-Insecure-Requests=1&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F86.0.4240.198+Safari%2F537.36&Accept=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2Cimage%2Favif%2Cimage%2Fwebp%2Cimage%2Fapng%2C%2A%2F%2A%3Bq%3D0.8%2Capplication%2Fsigned-exchange%3Bv%3Db3%3Bq%3D0.9&Accept-Encoding=gzip%2C+deflate%2C+br&Accept-Language=zh-CN%2Czh%3Bq%3D0.9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[53512] Failed to execute script 'Download_SS_PDF ver1.8' due to unhandled exception!
PS D:\Downloads>

[/code]

**Comment by DertahSama** [comment]
是《[量子化学和量子物理题解](https://www.sslibrary.com/book/card?cnFenlei=O641.121-44&ssid=10253709&d=745aec692bfb5d45a00da7d95e5e58f2&isFromBW=false&isjgptjs=false&fromType=portal)》这本书吗？

我试了一下，我这边是可以正常下载的啊
![image](https://github.com/DertahSama/Download_SS_PDF/assets/74524914/e1bb7d68-d938-4091-a019-b71fafd59475)
![image](https://github.com/DertahSama/Download_SS_PDF/assets/74524914/fac6f75a-16be-4ef7-a10a-dd101a14315e)

我这边是教育网，不需要登录账号就能下载；看报错，我推测也许你那边是登录个人账号下载的，而这个脚本没有登录账号的功能，所以就访问不了了？

这个问题我不知道咋解决……不过所谓狡兔三窟，你可以试试另一个下载路子：http://tushu.163pdf.xyz/index.html

**Comment by jiucenglou** [comment]
> 是《[量子化学和量子物理题解](https://www.sslibrary.com/book/card?cnFenlei=O641.121-44&ssid=10253709&d=745aec692bfb5d45a00da7d95e5e58f2&isFromBW=false&isjgptjs=false&fromType=portal)》这本书吗？
> 
> 我试了一下，我这边是可以正常下载的啊 ![image](https://private-user-images.githubusercontent.com/74524914/307533717-e1bb7d68-d938-4091-a019-b71fafd59475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Njk2NTYsIm5iZiI6MTcwODg2OTM1NiwicGF0aCI6Ii83NDUyNDkxNC8zMDc1MzM3MTctZTFiYjdkNjgtZDkzOC00MDkxLWEwMTktYjcxZmFmZDU5NDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEzNTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MTk5OTI3OTYyYThkMDBhNGNjYTJlMzAzZmYxNGRlNGI3ODQxODNkZjRmMWYxZmE0N2Y0OTk1ODg4ZmQ4OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XSGLxboPXXKvADb5-aBzFfiOGBQPyyLIu71SI3AAP_k) ![image](https://private-user-images.githubusercontent.com/74524914/307533760-fac6f75a-16be-4ef7-a10a-dd101a14315e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Njk2NTYsIm5iZiI6MTcwODg2OTM1NiwicGF0aCI6Ii83NDUyNDkxNC8zMDc1MzM3NjAtZmFjNmY3NWEtMTZiZS00ZWY3LWExMGEtZGQxMDFhMTQzMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEzNTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZWEzNWQ0M2Y5MTk1ZDRjOTU4YjZlNzc0ZmZlOWZhN2Y2MWIzNWI1ZDMxZTlkMmMyMjZmNjA5OTU1NDg5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXc7sPdvHwVIgKupe9VlNLRa0NbtdQ8c9Th8AfhaGsk)
> 
> 我这边是教育网，不需要登录账号就能下载；看报错，我推测也许你那边是登录个人账号下载的，而这个脚本没有登录账号的功能，所以就访问不了了？
> 
> 这个问题我不知道咋解决……不过所谓狡兔三窟，你可以试试另一个下载路子：http://tushu.163pdf.xyz/index.html

经您提醒，直连网络后又试了一次，可以下载了！谢谢！！
