### ISSUE TITLE
运行显示错误：Exception: 获取信息失败，网址可能已超时。

### ISSUE THREAD

**Issue by HeRuiDong12138** [DertahSama/Download_SS_PDF#2]
试了好几本书，都是这样报错的。
我的步骤是：
1.选一本书，选择PDF阅读，进入在线阅读器。
2.运行python文件，提示输入网址。
3.在阅读器界面，复制网址，网页没有关闭。
4.输入终端，回车确认，然后就报错了。

**Comment by DertahSama** [comment]
下的什么书啊？我试试

**Comment by HeRuiDong12138** [comment]
感谢作者大大回复！我是用校园网，跳转至贵州省图书馆的。书籍信息是：


其阅读器链接为：控制系统MATLAB仿真--阅读 (sslibrary.com)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月29日(星期天) 中午1:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DertahSama/Download_SS_PDF] 运行显示错误：Exception: 获取信息失败，网址可能已超时。 (Issue #2)





 
下的什么书啊？我试试

**Comment by DertahSama** [comment]
我看了下你的书，应该是2021年北理工出版社出版的那本吧？
对于近几年新出的书，超星图书馆升级了系统，可以提供原生电子版pdf，其阅读器网址是 ssj.sslibrary.com 打头的，特点是其中的文字放大不失真而且可以直接选中复制；
而我这个脚本的原理只是保存图片，只能处理 img.sslibrary.com 打头的阅读器网址，这里的书就是普通扫描版，其中每一页就只是一张图片。

**所以对于这种新式的阅读器，本脚本是无效的……**

不过还是有解决办法的！这些新书依旧有旧式扫描版的，你可以上**读秀**（book.duxiu.com），这里同时提供了新式阅读器（「书世界」）和旧式阅读器（「汇雅电子书」）的进入链接，**你进这个「汇雅电子书」的页面，就是本脚本能处理的页面了。**
![snipaste_20220529_132917](https://user-images.githubusercontent.com/74524914/170853850-61c070db-4113-4e1e-a129-26a8c1222d7b.jpg)

我之前也发现了这个问题但是没理会，我还是在使用方法里明确一下吧~

**Comment by HeRuiDong12138** [comment]
首先，很感谢您的帮助！
但我在读秀界面，并没有从获取途径看到“汇雅电子书”。经过摸索，我发现：
1.如果是新书，其旧式阅读器只支持部分阅读：

但可以通过图书馆文献传递得到全文，每天只能传递50页。

2.有些书，点击部分阅读会出现：

这类书籍就无法获取资源，只能通过文献传递得到。


3.2013年以前的书籍，均可根据作者大大的脚本进行下载，因为都是扫描全本的书籍。


最后，再次感谢作者大大的解答。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月29日(星期天) 中午1:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DertahSama/Download_SS_PDF] 运行显示错误：Exception: 获取信息失败，网址可能已超时。 (Issue #2)





 
我看了下你的书，应该是2021年北理工出版社出版的那本吧？
 对于近几年新出的书，超星图书馆升级了系统，可以提供原生电子版pdf，其阅读器网址是 ssj.sslibrary.com 打头的，特点是其中的文字放大不失真而且可以直接选中复制；
 而我这个脚本的原理只是保存图片，只能处理 img.sslibrary.com 打头的阅读器网址，这里的书就是普通扫描版，其中每一页就只是一张图片。
 
所以对于这种新式的阅读器，本脚本是无效的……
 
不过还是有解决办法的！这些新书依旧有旧式扫描版的，你可以上读秀（book.duxiu.com），这里同时提供了新式阅读器（「书世界」）和旧式阅读器（「汇雅电子书」）的进入链接，你进这个「汇雅电子书」的页面，就是本脚本能处理的页面了。
 
 
我之前也发现了这个问题但是没理会，我还是在使用方法里明确一下吧~

**Comment by DertahSama** [comment]
我又找到一个办法，不需要读秀：

上面那本书，在超星图书馆自己的搜索里，「PDF阅读」的链接复制出来是：
https://www.sslibrary.com/reader/pdf/pdfreader?ssid=14927513&d=24de95b0ebcb8edea244ea5522bfdb3a

只要把这里的两处`pdf`都改成`jpath`，就能进入旧式阅读器了：
https://www.sslibrary.com/reader/jpath/jpathreader?ssid=14927513&d=24de95b0ebcb8edea244ea5522bfdb3a

你试试看，行不行？

另外读秀那个「文献传递」纯坑爹的，不会让你下完，在你还有最后一次就能传递完全书的时候就不给你传递了……
如果本脚本下有些书反复失败不得劲的话，可以上盗版网站试试：https://wenxian11.cn/ ，这些人直接扒了超星的整个数据库，19年前的书似乎都在。

**Comment by HeRuiDong12138** [comment]
经过测试，pdf更改为jpath成功进入旧式阅读器，并成功利用作者大大的脚本下载成功！
此处，我向您的帮助表示感谢，并向您致意。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月29日(星期天) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DertahSama/Download_SS_PDF] 运行显示错误：Exception: 获取信息失败，网址可能已超时。 (Issue #2)





 
我又找到一个办法，不需要读秀：
 
上面那本书，在超星图书馆自己的搜索里，「PDF阅读」的链接复制出来是：
 https://www.sslibrary.com/reader/pdf/pdfreader?ssid=14927513&amp;d=24de95b0ebcb8edea244ea5522bfdb3a
 
只要把这里的两处pdf都改成jpath，就能进入旧式阅读器了：
 https://www.sslibrary.com/reader/jpath/jpathreader?ssid=14927513&amp;d=24de95b0ebcb8edea244ea5522bfdb3a
 
你试试看，行不行？
 
另外读秀那个「文献传递」纯坑爹的，不会让你下完，在你还有最后一次就能传递完全书的时候就不给你传递了……
 如果本脚本下有些书反复失败不得劲的话，可以上盗版网站试试：https://wenxian11.cn/ ，这些人直接扒了超星的整个数据库，19年前的书似乎都在。

**Comment by DertahSama** [comment]
(*๓´╰╯`๓)那就好~那这个issue我就关掉了
