### ISSUE TITLE
关于 ssj.sslibrary.com 的情报

### ISSUE THREAD

**Issue by 954-Ivory** [DertahSama/Download_SS_PDF#6]
没什么高并发爬取的需求，或许能用 Selenium 实现一套？
不过这两天比较懒，不想写代码。

**Comment by DertahSama** [comment]
emmm……？没懂你啥意思，是说用Selenium更好吗？但我并不会啊…

**Comment by 954-Ivory** [comment]
> emmm……？没懂你啥意思，是说用Selenium更好吗？但我并不会啊…

`ssj.sslibrary.com` 看起来是做了些反爬机制，对爬取效率没有要求时，模拟浏览器真实的动作最容易实现。
毕竟有些反爬操作，你就算花时间也很难解出来。
Selenium 本来是用来做测试的，但是这玩意儿在这种场景还是挺适用的，有空你可以研究下。

**Comment by 954-Ivory** [comment]
这几天闲着蛋疼，对`ssj.sslibrary.com`下手了，没上Selenium，纯抓包+requests。
但是验证码那块，用了识别库，伪造请求依然不生效。
貌似访问过于频繁，我的账号就被封了，看来下次写爬虫不能用主账号。
/(ㄒoㄒ)/~~
